abstract: Compiler for Perl 6 Rules
author: The Pugs Team <perl6-compiler@perl.org>.
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Pugs-Compiler-Rule
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
version: 0.05
