abstract: Compiler for Perl 6 Rules
author: The Pugs Team C<< <perl6-compiler@perl.org> >>.
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Pugs-Compiler-Rule
no_index:
  directory:
    - inc
    - t
requires:
  Cache::Cache: 1.05
  Class::InsideOut: 0
  Data::Dump::Streamer: 0
  PadWalker: 1.0
  Parse::Yapp: 0
  perl: 5.6.0
version: 0.13
