--- 
abstract: Compiler for Perl 6 regexes
author: The Pugs Team C<< <perl6-compiler@perl.org> >>.
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Pugs-Compiler-Rule
no_index: 
  directory: 
    - inc
    - t
recommends: 
  YAML::Syck: 0.60
requires: 
  Cache::Cache: 1.05
  File::Slurp: 0
  PadWalker: 1.0
  Parse::Yapp: 0
  perl: 5.6.1
tests: t/*.t t/*/*.t
version: 0.25
